spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:account
    username: sa
    password:
    driver-class-name: org.h2.Driver
  application:
    name : bdd-ms-account-service
server:
  port: 9090